// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dot_data.proto

package gov.nist.perfloc;

public final class DotData {
  private DotData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DotReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfloc.DotReading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 dot_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a Dot marking
     * </pre>
     */
    boolean hasDotNr();
    /**
     * <code>optional int32 dot_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a Dot marking
     * </pre>
     */
    int getDotNr();

    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code perfloc.DotReading}
   */
  public static final class DotReading extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:perfloc.DotReading)
      DotReadingOrBuilder {
    // Use DotReading.newBuilder() to construct.
    private DotReading(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DotReading(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DotReading defaultInstance;
    public static DotReading getDefaultInstance() {
      return defaultInstance;
    }

    public DotReading getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DotReading(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              dotNr_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.nist.perfloc.DotData.internal_static_perfloc_DotReading_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.nist.perfloc.DotData.internal_static_perfloc_DotReading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.nist.perfloc.DotData.DotReading.class, gov.nist.perfloc.DotData.DotReading.Builder.class);
    }

    public static com.google.protobuf.Parser<DotReading> PARSER =
        new com.google.protobuf.AbstractParser<DotReading>() {
      public DotReading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DotReading(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DotReading> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DOT_NR_FIELD_NUMBER = 1;
    private int dotNr_;
    /**
     * <code>optional int32 dot_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a Dot marking
     * </pre>
     */
    public boolean hasDotNr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 dot_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a Dot marking
     * </pre>
     */
    public int getDotNr() {
      return dotNr_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      dotNr_ = 0;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, dotNr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, dotNr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gov.nist.perfloc.DotData.DotReading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gov.nist.perfloc.DotData.DotReading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gov.nist.perfloc.DotData.DotReading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gov.nist.perfloc.DotData.DotReading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gov.nist.perfloc.DotData.DotReading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gov.nist.perfloc.DotData.DotReading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gov.nist.perfloc.DotData.DotReading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gov.nist.perfloc.DotData.DotReading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gov.nist.perfloc.DotData.DotReading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gov.nist.perfloc.DotData.DotReading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gov.nist.perfloc.DotData.DotReading prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code perfloc.DotReading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfloc.DotReading)
        gov.nist.perfloc.DotData.DotReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gov.nist.perfloc.DotData.internal_static_perfloc_DotReading_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gov.nist.perfloc.DotData.internal_static_perfloc_DotReading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gov.nist.perfloc.DotData.DotReading.class, gov.nist.perfloc.DotData.DotReading.Builder.class);
      }

      // Construct using gov.nist.perfloc.DotData.DotReading.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dotNr_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gov.nist.perfloc.DotData.internal_static_perfloc_DotReading_descriptor;
      }

      public gov.nist.perfloc.DotData.DotReading getDefaultInstanceForType() {
        return gov.nist.perfloc.DotData.DotReading.getDefaultInstance();
      }

      public gov.nist.perfloc.DotData.DotReading build() {
        gov.nist.perfloc.DotData.DotReading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gov.nist.perfloc.DotData.DotReading buildPartial() {
        gov.nist.perfloc.DotData.DotReading result = new gov.nist.perfloc.DotData.DotReading(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dotNr_ = dotNr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gov.nist.perfloc.DotData.DotReading) {
          return mergeFrom((gov.nist.perfloc.DotData.DotReading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gov.nist.perfloc.DotData.DotReading other) {
        if (other == gov.nist.perfloc.DotData.DotReading.getDefaultInstance()) return this;
        if (other.hasDotNr()) {
          setDotNr(other.getDotNr());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gov.nist.perfloc.DotData.DotReading parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gov.nist.perfloc.DotData.DotReading) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int dotNr_ ;
      /**
       * <code>optional int32 dot_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a Dot marking
       * </pre>
       */
      public boolean hasDotNr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 dot_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a Dot marking
       * </pre>
       */
      public int getDotNr() {
        return dotNr_;
      }
      /**
       * <code>optional int32 dot_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a Dot marking
       * </pre>
       */
      public Builder setDotNr(int value) {
        bitField0_ |= 0x00000001;
        dotNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 dot_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a Dot marking
       * </pre>
       */
      public Builder clearDotNr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dotNr_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:perfloc.DotReading)
    }

    static {
      defaultInstance = new DotReading(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:perfloc.DotReading)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfloc_DotReading_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_perfloc_DotReading_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016dot_data.proto\022\007perfloc\"/\n\nDotReading\022" +
      "\016\n\006dot_nr\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001(\003B\022\n\020go" +
      "v.nist.perfloc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_perfloc_DotReading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfloc_DotReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_perfloc_DotReading_descriptor,
        new java.lang.String[] { "DotNr", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
