// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wifi_data.proto

package gov.nist.perfloc;

public final class WifiData {
  private WifiData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WiFiReadingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfloc.WiFiReading)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 sequence_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a reading
     * </pre>
     */
    boolean hasSequenceNr();
    /**
     * <code>optional int32 sequence_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a reading
     * </pre>
     */
    int getSequenceNr();

    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    long getTimestamp();

    /**
     * <code>optional int32 last_dot_nr = 3;</code>
     *
     * <pre>
     * Location where the measurment was taken
     * </pre>
     */
    boolean hasLastDotNr();
    /**
     * <code>optional int32 last_dot_nr = 3;</code>
     *
     * <pre>
     * Location where the measurment was taken
     * </pre>
     */
    int getLastDotNr();

    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    java.util.List<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP> 
        getWifiApList();
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    gov.nist.perfloc.WifiData.WiFiReading.WiFiAP getWifiAp(int index);
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    int getWifiApCount();
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    java.util.List<? extends gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder> 
        getWifiApOrBuilderList();
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder getWifiApOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code perfloc.WiFiReading}
   */
  public static final class WiFiReading extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:perfloc.WiFiReading)
      WiFiReadingOrBuilder {
    // Use WiFiReading.newBuilder() to construct.
    private WiFiReading(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WiFiReading(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WiFiReading defaultInstance;
    public static WiFiReading getDefaultInstance() {
      return defaultInstance;
    }

    public WiFiReading getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WiFiReading(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              sequenceNr_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              lastDotNr_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                wifiAp_ = new java.util.ArrayList<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP>();
                mutable_bitField0_ |= 0x00000008;
              }
              wifiAp_.add(input.readMessage(gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          wifiAp_ = java.util.Collections.unmodifiableList(wifiAp_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gov.nist.perfloc.WifiData.WiFiReading.class, gov.nist.perfloc.WifiData.WiFiReading.Builder.class);
    }

    public static com.google.protobuf.Parser<WiFiReading> PARSER =
        new com.google.protobuf.AbstractParser<WiFiReading>() {
      public WiFiReading parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WiFiReading(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WiFiReading> getParserForType() {
      return PARSER;
    }

    public interface WiFiAPOrBuilder extends
        // @@protoc_insertion_point(interface_extends:perfloc.WiFiReading.WiFiAP)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string bssid = 1;</code>
       *
       * <pre>
       * The address of the access point
       * </pre>
       */
      boolean hasBssid();
      /**
       * <code>optional string bssid = 1;</code>
       *
       * <pre>
       * The address of the access point
       * </pre>
       */
      java.lang.String getBssid();
      /**
       * <code>optional string bssid = 1;</code>
       *
       * <pre>
       * The address of the access point
       * </pre>
       */
      com.google.protobuf.ByteString
          getBssidBytes();

      /**
       * <code>optional string ssid = 2;</code>
       *
       * <pre>
       * The network name
       * </pre>
       */
      boolean hasSsid();
      /**
       * <code>optional string ssid = 2;</code>
       *
       * <pre>
       * The network name
       * </pre>
       */
      java.lang.String getSsid();
      /**
       * <code>optional string ssid = 2;</code>
       *
       * <pre>
       * The network name
       * </pre>
       */
      com.google.protobuf.ByteString
          getSsidBytes();

      /**
       * <code>optional string capabilities = 3;</code>
       *
       * <pre>
       * The authentication, key management, and encryption schemes supported by the access point
       * </pre>
       */
      boolean hasCapabilities();
      /**
       * <code>optional string capabilities = 3;</code>
       *
       * <pre>
       * The authentication, key management, and encryption schemes supported by the access point
       * </pre>
       */
      java.lang.String getCapabilities();
      /**
       * <code>optional string capabilities = 3;</code>
       *
       * <pre>
       * The authentication, key management, and encryption schemes supported by the access point
       * </pre>
       */
      com.google.protobuf.ByteString
          getCapabilitiesBytes();

      /**
       * <code>optional int32 frequency = 4;</code>
       *
       * <pre>
       * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
       * </pre>
       */
      boolean hasFrequency();
      /**
       * <code>optional int32 frequency = 4;</code>
       *
       * <pre>
       * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
       * </pre>
       */
      int getFrequency();

      /**
       * <code>optional int32 rssi = 5;</code>
       *
       * <pre>
       * The detected signal level in dBm, also known as the RSSI
       * </pre>
       */
      boolean hasRssi();
      /**
       * <code>optional int32 rssi = 5;</code>
       *
       * <pre>
       * The detected signal level in dBm, also known as the RSSI
       * </pre>
       */
      int getRssi();

      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       * timestamp in microseconds (since boot) when this result was last seen
       * </pre>
       */
      boolean hasTimestamp();
      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       * timestamp in microseconds (since boot) when this result was last seen
       * </pre>
       */
      long getTimestamp();
    }
    /**
     * Protobuf type {@code perfloc.WiFiReading.WiFiAP}
     */
    public static final class WiFiAP extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:perfloc.WiFiReading.WiFiAP)
        WiFiAPOrBuilder {
      // Use WiFiAP.newBuilder() to construct.
      private WiFiAP(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private WiFiAP(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final WiFiAP defaultInstance;
      public static WiFiAP getDefaultInstance() {
        return defaultInstance;
      }

      public WiFiAP getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private WiFiAP(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                bssid_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                ssid_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                capabilities_ = bs;
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                frequency_ = input.readInt32();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                rssi_ = input.readInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                timestamp_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_WiFiAP_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_WiFiAP_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.class, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder.class);
      }

      public static com.google.protobuf.Parser<WiFiAP> PARSER =
          new com.google.protobuf.AbstractParser<WiFiAP>() {
        public WiFiAP parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new WiFiAP(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<WiFiAP> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int BSSID_FIELD_NUMBER = 1;
      private java.lang.Object bssid_;
      /**
       * <code>optional string bssid = 1;</code>
       *
       * <pre>
       * The address of the access point
       * </pre>
       */
      public boolean hasBssid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string bssid = 1;</code>
       *
       * <pre>
       * The address of the access point
       * </pre>
       */
      public java.lang.String getBssid() {
        java.lang.Object ref = bssid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bssid_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string bssid = 1;</code>
       *
       * <pre>
       * The address of the access point
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        java.lang.Object ref = bssid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SSID_FIELD_NUMBER = 2;
      private java.lang.Object ssid_;
      /**
       * <code>optional string ssid = 2;</code>
       *
       * <pre>
       * The network name
       * </pre>
       */
      public boolean hasSsid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string ssid = 2;</code>
       *
       * <pre>
       * The network name
       * </pre>
       */
      public java.lang.String getSsid() {
        java.lang.Object ref = ssid_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ssid_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string ssid = 2;</code>
       *
       * <pre>
       * The network name
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        java.lang.Object ref = ssid_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CAPABILITIES_FIELD_NUMBER = 3;
      private java.lang.Object capabilities_;
      /**
       * <code>optional string capabilities = 3;</code>
       *
       * <pre>
       * The authentication, key management, and encryption schemes supported by the access point
       * </pre>
       */
      public boolean hasCapabilities() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string capabilities = 3;</code>
       *
       * <pre>
       * The authentication, key management, and encryption schemes supported by the access point
       * </pre>
       */
      public java.lang.String getCapabilities() {
        java.lang.Object ref = capabilities_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            capabilities_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string capabilities = 3;</code>
       *
       * <pre>
       * The authentication, key management, and encryption schemes supported by the access point
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCapabilitiesBytes() {
        java.lang.Object ref = capabilities_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          capabilities_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int FREQUENCY_FIELD_NUMBER = 4;
      private int frequency_;
      /**
       * <code>optional int32 frequency = 4;</code>
       *
       * <pre>
       * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
       * </pre>
       */
      public boolean hasFrequency() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 frequency = 4;</code>
       *
       * <pre>
       * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
       * </pre>
       */
      public int getFrequency() {
        return frequency_;
      }

      public static final int RSSI_FIELD_NUMBER = 5;
      private int rssi_;
      /**
       * <code>optional int32 rssi = 5;</code>
       *
       * <pre>
       * The detected signal level in dBm, also known as the RSSI
       * </pre>
       */
      public boolean hasRssi() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 rssi = 5;</code>
       *
       * <pre>
       * The detected signal level in dBm, also known as the RSSI
       * </pre>
       */
      public int getRssi() {
        return rssi_;
      }

      public static final int TIMESTAMP_FIELD_NUMBER = 6;
      private long timestamp_;
      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       * timestamp in microseconds (since boot) when this result was last seen
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 timestamp = 6;</code>
       *
       * <pre>
       * timestamp in microseconds (since boot) when this result was last seen
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }

      private void initFields() {
        bssid_ = "";
        ssid_ = "";
        capabilities_ = "";
        frequency_ = 0;
        rssi_ = 0;
        timestamp_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getBssidBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getSsidBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getCapabilitiesBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, frequency_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(5, rssi_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeInt64(6, timestamp_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getBssidBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getSsidBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getCapabilitiesBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, frequency_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, rssi_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(6, timestamp_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gov.nist.perfloc.WifiData.WiFiReading.WiFiAP prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code perfloc.WiFiReading.WiFiAP}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:perfloc.WiFiReading.WiFiAP)
          gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_WiFiAP_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_WiFiAP_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.class, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder.class);
        }

        // Construct using gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          bssid_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          ssid_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          capabilities_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          frequency_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          rssi_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          timestamp_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000020);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_WiFiAP_descriptor;
        }

        public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP getDefaultInstanceForType() {
          return gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.getDefaultInstance();
        }

        public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP build() {
          gov.nist.perfloc.WifiData.WiFiReading.WiFiAP result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP buildPartial() {
          gov.nist.perfloc.WifiData.WiFiReading.WiFiAP result = new gov.nist.perfloc.WifiData.WiFiReading.WiFiAP(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.bssid_ = bssid_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.ssid_ = ssid_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.capabilities_ = capabilities_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.frequency_ = frequency_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.rssi_ = rssi_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.timestamp_ = timestamp_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gov.nist.perfloc.WifiData.WiFiReading.WiFiAP) {
            return mergeFrom((gov.nist.perfloc.WifiData.WiFiReading.WiFiAP)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gov.nist.perfloc.WifiData.WiFiReading.WiFiAP other) {
          if (other == gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.getDefaultInstance()) return this;
          if (other.hasBssid()) {
            bitField0_ |= 0x00000001;
            bssid_ = other.bssid_;
            onChanged();
          }
          if (other.hasSsid()) {
            bitField0_ |= 0x00000002;
            ssid_ = other.ssid_;
            onChanged();
          }
          if (other.hasCapabilities()) {
            bitField0_ |= 0x00000004;
            capabilities_ = other.capabilities_;
            onChanged();
          }
          if (other.hasFrequency()) {
            setFrequency(other.getFrequency());
          }
          if (other.hasRssi()) {
            setRssi(other.getRssi());
          }
          if (other.hasTimestamp()) {
            setTimestamp(other.getTimestamp());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          gov.nist.perfloc.WifiData.WiFiReading.WiFiAP parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (gov.nist.perfloc.WifiData.WiFiReading.WiFiAP) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object bssid_ = "";
        /**
         * <code>optional string bssid = 1;</code>
         *
         * <pre>
         * The address of the access point
         * </pre>
         */
        public boolean hasBssid() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string bssid = 1;</code>
         *
         * <pre>
         * The address of the access point
         * </pre>
         */
        public java.lang.String getBssid() {
          java.lang.Object ref = bssid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              bssid_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string bssid = 1;</code>
         *
         * <pre>
         * The address of the access point
         * </pre>
         */
        public com.google.protobuf.ByteString
            getBssidBytes() {
          java.lang.Object ref = bssid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            bssid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string bssid = 1;</code>
         *
         * <pre>
         * The address of the access point
         * </pre>
         */
        public Builder setBssid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          bssid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string bssid = 1;</code>
         *
         * <pre>
         * The address of the access point
         * </pre>
         */
        public Builder clearBssid() {
          bitField0_ = (bitField0_ & ~0x00000001);
          bssid_ = getDefaultInstance().getBssid();
          onChanged();
          return this;
        }
        /**
         * <code>optional string bssid = 1;</code>
         *
         * <pre>
         * The address of the access point
         * </pre>
         */
        public Builder setBssidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          bssid_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object ssid_ = "";
        /**
         * <code>optional string ssid = 2;</code>
         *
         * <pre>
         * The network name
         * </pre>
         */
        public boolean hasSsid() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string ssid = 2;</code>
         *
         * <pre>
         * The network name
         * </pre>
         */
        public java.lang.String getSsid() {
          java.lang.Object ref = ssid_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              ssid_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string ssid = 2;</code>
         *
         * <pre>
         * The network name
         * </pre>
         */
        public com.google.protobuf.ByteString
            getSsidBytes() {
          java.lang.Object ref = ssid_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ssid_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string ssid = 2;</code>
         *
         * <pre>
         * The network name
         * </pre>
         */
        public Builder setSsid(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          ssid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string ssid = 2;</code>
         *
         * <pre>
         * The network name
         * </pre>
         */
        public Builder clearSsid() {
          bitField0_ = (bitField0_ & ~0x00000002);
          ssid_ = getDefaultInstance().getSsid();
          onChanged();
          return this;
        }
        /**
         * <code>optional string ssid = 2;</code>
         *
         * <pre>
         * The network name
         * </pre>
         */
        public Builder setSsidBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          ssid_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object capabilities_ = "";
        /**
         * <code>optional string capabilities = 3;</code>
         *
         * <pre>
         * The authentication, key management, and encryption schemes supported by the access point
         * </pre>
         */
        public boolean hasCapabilities() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string capabilities = 3;</code>
         *
         * <pre>
         * The authentication, key management, and encryption schemes supported by the access point
         * </pre>
         */
        public java.lang.String getCapabilities() {
          java.lang.Object ref = capabilities_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              capabilities_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string capabilities = 3;</code>
         *
         * <pre>
         * The authentication, key management, and encryption schemes supported by the access point
         * </pre>
         */
        public com.google.protobuf.ByteString
            getCapabilitiesBytes() {
          java.lang.Object ref = capabilities_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            capabilities_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string capabilities = 3;</code>
         *
         * <pre>
         * The authentication, key management, and encryption schemes supported by the access point
         * </pre>
         */
        public Builder setCapabilities(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          capabilities_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string capabilities = 3;</code>
         *
         * <pre>
         * The authentication, key management, and encryption schemes supported by the access point
         * </pre>
         */
        public Builder clearCapabilities() {
          bitField0_ = (bitField0_ & ~0x00000004);
          capabilities_ = getDefaultInstance().getCapabilities();
          onChanged();
          return this;
        }
        /**
         * <code>optional string capabilities = 3;</code>
         *
         * <pre>
         * The authentication, key management, and encryption schemes supported by the access point
         * </pre>
         */
        public Builder setCapabilitiesBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          capabilities_ = value;
          onChanged();
          return this;
        }

        private int frequency_ ;
        /**
         * <code>optional int32 frequency = 4;</code>
         *
         * <pre>
         * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
         * </pre>
         */
        public boolean hasFrequency() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 frequency = 4;</code>
         *
         * <pre>
         * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
         * </pre>
         */
        public int getFrequency() {
          return frequency_;
        }
        /**
         * <code>optional int32 frequency = 4;</code>
         *
         * <pre>
         * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
         * </pre>
         */
        public Builder setFrequency(int value) {
          bitField0_ |= 0x00000008;
          frequency_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 frequency = 4;</code>
         *
         * <pre>
         * The primary 20 MHz frequency (in Mhz) of the channel over which the client is communicating with the access point
         * </pre>
         */
        public Builder clearFrequency() {
          bitField0_ = (bitField0_ & ~0x00000008);
          frequency_ = 0;
          onChanged();
          return this;
        }

        private int rssi_ ;
        /**
         * <code>optional int32 rssi = 5;</code>
         *
         * <pre>
         * The detected signal level in dBm, also known as the RSSI
         * </pre>
         */
        public boolean hasRssi() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional int32 rssi = 5;</code>
         *
         * <pre>
         * The detected signal level in dBm, also known as the RSSI
         * </pre>
         */
        public int getRssi() {
          return rssi_;
        }
        /**
         * <code>optional int32 rssi = 5;</code>
         *
         * <pre>
         * The detected signal level in dBm, also known as the RSSI
         * </pre>
         */
        public Builder setRssi(int value) {
          bitField0_ |= 0x00000010;
          rssi_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 rssi = 5;</code>
         *
         * <pre>
         * The detected signal level in dBm, also known as the RSSI
         * </pre>
         */
        public Builder clearRssi() {
          bitField0_ = (bitField0_ & ~0x00000010);
          rssi_ = 0;
          onChanged();
          return this;
        }

        private long timestamp_ ;
        /**
         * <code>optional int64 timestamp = 6;</code>
         *
         * <pre>
         * timestamp in microseconds (since boot) when this result was last seen
         * </pre>
         */
        public boolean hasTimestamp() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional int64 timestamp = 6;</code>
         *
         * <pre>
         * timestamp in microseconds (since boot) when this result was last seen
         * </pre>
         */
        public long getTimestamp() {
          return timestamp_;
        }
        /**
         * <code>optional int64 timestamp = 6;</code>
         *
         * <pre>
         * timestamp in microseconds (since boot) when this result was last seen
         * </pre>
         */
        public Builder setTimestamp(long value) {
          bitField0_ |= 0x00000020;
          timestamp_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 timestamp = 6;</code>
         *
         * <pre>
         * timestamp in microseconds (since boot) when this result was last seen
         * </pre>
         */
        public Builder clearTimestamp() {
          bitField0_ = (bitField0_ & ~0x00000020);
          timestamp_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:perfloc.WiFiReading.WiFiAP)
      }

      static {
        defaultInstance = new WiFiAP(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:perfloc.WiFiReading.WiFiAP)
    }

    private int bitField0_;
    public static final int SEQUENCE_NR_FIELD_NUMBER = 1;
    private int sequenceNr_;
    /**
     * <code>optional int32 sequence_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a reading
     * </pre>
     */
    public boolean hasSequenceNr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 sequence_nr = 1;</code>
     *
     * <pre>
     * Sequence number of a reading
     * </pre>
     */
    public int getSequenceNr() {
      return sequenceNr_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     * Time of this scan in milliseconds
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int LAST_DOT_NR_FIELD_NUMBER = 3;
    private int lastDotNr_;
    /**
     * <code>optional int32 last_dot_nr = 3;</code>
     *
     * <pre>
     * Location where the measurment was taken
     * </pre>
     */
    public boolean hasLastDotNr() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 last_dot_nr = 3;</code>
     *
     * <pre>
     * Location where the measurment was taken
     * </pre>
     */
    public int getLastDotNr() {
      return lastDotNr_;
    }

    public static final int WIFI_AP_FIELD_NUMBER = 4;
    private java.util.List<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP> wifiAp_;
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    public java.util.List<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP> getWifiApList() {
      return wifiAp_;
    }
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    public java.util.List<? extends gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder> 
        getWifiApOrBuilderList() {
      return wifiAp_;
    }
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    public int getWifiApCount() {
      return wifiAp_.size();
    }
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP getWifiAp(int index) {
      return wifiAp_.get(index);
    }
    /**
     * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
     *
     * <pre>
     * Format defining a WiFi access point
     * </pre>
     */
    public gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder getWifiApOrBuilder(
        int index) {
      return wifiAp_.get(index);
    }

    private void initFields() {
      sequenceNr_ = 0;
      timestamp_ = 0L;
      lastDotNr_ = 0;
      wifiAp_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, sequenceNr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, lastDotNr_);
      }
      for (int i = 0; i < wifiAp_.size(); i++) {
        output.writeMessage(4, wifiAp_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sequenceNr_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, lastDotNr_);
      }
      for (int i = 0; i < wifiAp_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, wifiAp_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gov.nist.perfloc.WifiData.WiFiReading parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gov.nist.perfloc.WifiData.WiFiReading prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code perfloc.WiFiReading}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfloc.WiFiReading)
        gov.nist.perfloc.WifiData.WiFiReadingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gov.nist.perfloc.WifiData.WiFiReading.class, gov.nist.perfloc.WifiData.WiFiReading.Builder.class);
      }

      // Construct using gov.nist.perfloc.WifiData.WiFiReading.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getWifiApFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sequenceNr_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        lastDotNr_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (wifiApBuilder_ == null) {
          wifiAp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          wifiApBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gov.nist.perfloc.WifiData.internal_static_perfloc_WiFiReading_descriptor;
      }

      public gov.nist.perfloc.WifiData.WiFiReading getDefaultInstanceForType() {
        return gov.nist.perfloc.WifiData.WiFiReading.getDefaultInstance();
      }

      public gov.nist.perfloc.WifiData.WiFiReading build() {
        gov.nist.perfloc.WifiData.WiFiReading result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gov.nist.perfloc.WifiData.WiFiReading buildPartial() {
        gov.nist.perfloc.WifiData.WiFiReading result = new gov.nist.perfloc.WifiData.WiFiReading(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sequenceNr_ = sequenceNr_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastDotNr_ = lastDotNr_;
        if (wifiApBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            wifiAp_ = java.util.Collections.unmodifiableList(wifiAp_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.wifiAp_ = wifiAp_;
        } else {
          result.wifiAp_ = wifiApBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gov.nist.perfloc.WifiData.WiFiReading) {
          return mergeFrom((gov.nist.perfloc.WifiData.WiFiReading)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gov.nist.perfloc.WifiData.WiFiReading other) {
        if (other == gov.nist.perfloc.WifiData.WiFiReading.getDefaultInstance()) return this;
        if (other.hasSequenceNr()) {
          setSequenceNr(other.getSequenceNr());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasLastDotNr()) {
          setLastDotNr(other.getLastDotNr());
        }
        if (wifiApBuilder_ == null) {
          if (!other.wifiAp_.isEmpty()) {
            if (wifiAp_.isEmpty()) {
              wifiAp_ = other.wifiAp_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureWifiApIsMutable();
              wifiAp_.addAll(other.wifiAp_);
            }
            onChanged();
          }
        } else {
          if (!other.wifiAp_.isEmpty()) {
            if (wifiApBuilder_.isEmpty()) {
              wifiApBuilder_.dispose();
              wifiApBuilder_ = null;
              wifiAp_ = other.wifiAp_;
              bitField0_ = (bitField0_ & ~0x00000008);
              wifiApBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getWifiApFieldBuilder() : null;
            } else {
              wifiApBuilder_.addAllMessages(other.wifiAp_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gov.nist.perfloc.WifiData.WiFiReading parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gov.nist.perfloc.WifiData.WiFiReading) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sequenceNr_ ;
      /**
       * <code>optional int32 sequence_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a reading
       * </pre>
       */
      public boolean hasSequenceNr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 sequence_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a reading
       * </pre>
       */
      public int getSequenceNr() {
        return sequenceNr_;
      }
      /**
       * <code>optional int32 sequence_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a reading
       * </pre>
       */
      public Builder setSequenceNr(int value) {
        bitField0_ |= 0x00000001;
        sequenceNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sequence_nr = 1;</code>
       *
       * <pre>
       * Sequence number of a reading
       * </pre>
       */
      public Builder clearSequenceNr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sequenceNr_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       * Time of this scan in milliseconds
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private int lastDotNr_ ;
      /**
       * <code>optional int32 last_dot_nr = 3;</code>
       *
       * <pre>
       * Location where the measurment was taken
       * </pre>
       */
      public boolean hasLastDotNr() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 last_dot_nr = 3;</code>
       *
       * <pre>
       * Location where the measurment was taken
       * </pre>
       */
      public int getLastDotNr() {
        return lastDotNr_;
      }
      /**
       * <code>optional int32 last_dot_nr = 3;</code>
       *
       * <pre>
       * Location where the measurment was taken
       * </pre>
       */
      public Builder setLastDotNr(int value) {
        bitField0_ |= 0x00000004;
        lastDotNr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 last_dot_nr = 3;</code>
       *
       * <pre>
       * Location where the measurment was taken
       * </pre>
       */
      public Builder clearLastDotNr() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastDotNr_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP> wifiAp_ =
        java.util.Collections.emptyList();
      private void ensureWifiApIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          wifiAp_ = new java.util.ArrayList<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP>(wifiAp_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gov.nist.perfloc.WifiData.WiFiReading.WiFiAP, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder, gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder> wifiApBuilder_;

      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public java.util.List<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP> getWifiApList() {
        if (wifiApBuilder_ == null) {
          return java.util.Collections.unmodifiableList(wifiAp_);
        } else {
          return wifiApBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public int getWifiApCount() {
        if (wifiApBuilder_ == null) {
          return wifiAp_.size();
        } else {
          return wifiApBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP getWifiAp(int index) {
        if (wifiApBuilder_ == null) {
          return wifiAp_.get(index);
        } else {
          return wifiApBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder setWifiAp(
          int index, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP value) {
        if (wifiApBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWifiApIsMutable();
          wifiAp_.set(index, value);
          onChanged();
        } else {
          wifiApBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder setWifiAp(
          int index, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder builderForValue) {
        if (wifiApBuilder_ == null) {
          ensureWifiApIsMutable();
          wifiAp_.set(index, builderForValue.build());
          onChanged();
        } else {
          wifiApBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder addWifiAp(gov.nist.perfloc.WifiData.WiFiReading.WiFiAP value) {
        if (wifiApBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWifiApIsMutable();
          wifiAp_.add(value);
          onChanged();
        } else {
          wifiApBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder addWifiAp(
          int index, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP value) {
        if (wifiApBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWifiApIsMutable();
          wifiAp_.add(index, value);
          onChanged();
        } else {
          wifiApBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder addWifiAp(
          gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder builderForValue) {
        if (wifiApBuilder_ == null) {
          ensureWifiApIsMutable();
          wifiAp_.add(builderForValue.build());
          onChanged();
        } else {
          wifiApBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder addWifiAp(
          int index, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder builderForValue) {
        if (wifiApBuilder_ == null) {
          ensureWifiApIsMutable();
          wifiAp_.add(index, builderForValue.build());
          onChanged();
        } else {
          wifiApBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder addAllWifiAp(
          java.lang.Iterable<? extends gov.nist.perfloc.WifiData.WiFiReading.WiFiAP> values) {
        if (wifiApBuilder_ == null) {
          ensureWifiApIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, wifiAp_);
          onChanged();
        } else {
          wifiApBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder clearWifiAp() {
        if (wifiApBuilder_ == null) {
          wifiAp_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          wifiApBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public Builder removeWifiAp(int index) {
        if (wifiApBuilder_ == null) {
          ensureWifiApIsMutable();
          wifiAp_.remove(index);
          onChanged();
        } else {
          wifiApBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder getWifiApBuilder(
          int index) {
        return getWifiApFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder getWifiApOrBuilder(
          int index) {
        if (wifiApBuilder_ == null) {
          return wifiAp_.get(index);  } else {
          return wifiApBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public java.util.List<? extends gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder> 
           getWifiApOrBuilderList() {
        if (wifiApBuilder_ != null) {
          return wifiApBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(wifiAp_);
        }
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder addWifiApBuilder() {
        return getWifiApFieldBuilder().addBuilder(
            gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.getDefaultInstance());
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder addWifiApBuilder(
          int index) {
        return getWifiApFieldBuilder().addBuilder(
            index, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.getDefaultInstance());
      }
      /**
       * <code>repeated .perfloc.WiFiReading.WiFiAP wifi_ap = 4;</code>
       *
       * <pre>
       * Format defining a WiFi access point
       * </pre>
       */
      public java.util.List<gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder> 
           getWifiApBuilderList() {
        return getWifiApFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gov.nist.perfloc.WifiData.WiFiReading.WiFiAP, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder, gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder> 
          getWifiApFieldBuilder() {
        if (wifiApBuilder_ == null) {
          wifiApBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gov.nist.perfloc.WifiData.WiFiReading.WiFiAP, gov.nist.perfloc.WifiData.WiFiReading.WiFiAP.Builder, gov.nist.perfloc.WifiData.WiFiReading.WiFiAPOrBuilder>(
                  wifiAp_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          wifiAp_ = null;
        }
        return wifiApBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:perfloc.WiFiReading)
    }

    static {
      defaultInstance = new WiFiReading(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:perfloc.WiFiReading)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfloc_WiFiReading_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_perfloc_WiFiReading_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfloc_WiFiReading_WiFiAP_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_perfloc_WiFiReading_WiFiAP_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017wifi_data.proto\022\007perfloc\"\351\001\n\013WiFiReadi" +
      "ng\022\023\n\013sequence_nr\030\001 \001(\005\022\021\n\ttimestamp\030\002 \001" +
      "(\003\022\023\n\013last_dot_nr\030\003 \001(\005\022,\n\007wifi_ap\030\004 \003(\013" +
      "2\033.perfloc.WiFiReading.WiFiAP\032o\n\006WiFiAP\022" +
      "\r\n\005bssid\030\001 \001(\t\022\014\n\004ssid\030\002 \001(\t\022\024\n\014capabili" +
      "ties\030\003 \001(\t\022\021\n\tfrequency\030\004 \001(\005\022\014\n\004rssi\030\005 " +
      "\001(\005\022\021\n\ttimestamp\030\006 \001(\003B\022\n\020gov.nist.perfl" +
      "oc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_perfloc_WiFiReading_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfloc_WiFiReading_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_perfloc_WiFiReading_descriptor,
        new java.lang.String[] { "SequenceNr", "Timestamp", "LastDotNr", "WifiAp", });
    internal_static_perfloc_WiFiReading_WiFiAP_descriptor =
      internal_static_perfloc_WiFiReading_descriptor.getNestedTypes().get(0);
    internal_static_perfloc_WiFiReading_WiFiAP_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_perfloc_WiFiReading_WiFiAP_descriptor,
        new java.lang.String[] { "Bssid", "Ssid", "Capabilities", "Frequency", "Rssi", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
